### ISSUE TITLE
[FEATURE] Is there a way for you to include removal of natural lava lakes?

### ISSUE THREAD

**Issue by bathala-a11y** [justsap/Evaporated-Waterfalls#1]
This mod is great but with the Lava Lakes being present I cant think of another mod or datapack that restricts lava lakes from spawning.

**Comment by justsap** [comment]
I could probably do that but, I would put it in a different datapack because the only purpose for this one is to reduce water & lava streams.

**Comment by makumaku1974** [comment]
> I could probably do that but, I would put it in a different datapack because the only purpose for this one is to reduce water & lava streams.

does this exclude waterfalls in one of the cave biomes? if not please exclude it.

**Comment by justsap** [comment]
It depends what you mean by waterfalls, because usually caves have local water levels and that creates waterfalls which IS NOT  what this datapack changes (because I have no clue how that works). This datapack only changes how those single source block waterfalls are generated, and if you were talking about that, it still generates in caves, but less often than vanilla. But my goal with this datapack was to reduce surface level waterfalls because it really annoyed me. Although I may be open to reducing it in caves as well but for right now I don't have the motivation to.
